/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ajpassignment.*;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wee Kiat
 */
public class BusStopInfoForm extends javax.swing.JDialog {

    /**
     * Creates new form BusStopInfoForm
     * @param bus_stop
     */
    private BusStop CurrentBusStop;
    
    public BusStopInfoForm(javax.swing.JFrame owner,BusStop bus_stop) {
        super(owner,true);
        initComponents();
        setLocationRelativeTo(null);
        
        CurrentBusStop = bus_stop;
        
        lBSNumber.setText("<html>Bus Stop Number:<br>" + CurrentBusStop.GetBusStopCode() + "</html>");
        lBSDesc.setText("<html>Bus Stop Description:<br>" + CurrentBusStop.GetBusStopDesc()+ "</html>");
        lRoadDesc.setText("<html>Road Description:<br>" + CurrentBusStop.GetRoadDesc()+ "</html>");
        
        ArrayList<Bus> buses = CurrentBusStop.GetBuses();
        DefaultTableModel model = (DefaultTableModel)TableBuses.getModel();
        for(Bus b : buses){
            model.addRow(new Object[]{ b.GetBusCode() });
        }
        
        TableBuses.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 1) {
                    JTable table =(JTable)me.getSource();
                    Point p = me.getPoint();
                    int row = table.rowAtPoint(p);
                    ShowBusRoute(row);
                }
            }
        });
        
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);
        TableBusRoute.getColumnModel().getColumn(0).setCellRenderer(leftRenderer);
    }

    private void ShowBusRoute(int BusRow)
    {
        Bus b = CurrentBusStop.GetBuses().get(BusRow);
        ArrayList<BusStop> bus_stops = b.GetRoute(CurrentBusStop);
        int i = 1;
        DefaultTableModel model = (DefaultTableModel)TableBusRoute.getModel();
        model.setRowCount(0);
        for(BusStop bs : bus_stops){
            model.addRow(new Object[]{ i++, bs.GetBusStopCode(),bs.GetBusStopDesc(),bs.GetRoadDesc()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lBSNumber = new javax.swing.JLabel();
        lBSDesc = new javax.swing.JLabel();
        lRoadDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBuses = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBusRoute = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bus Stop Info");

        lBSNumber.setText("Bus Stop Number:");
        lBSNumber.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lBSDesc.setText("Bus Stop Description:");
        lBSDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lRoadDesc.setText("Road Description:");
        lRoadDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TableBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableBuses);

        TableBusRoute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sequence", "Bus Stop Number", "Bus Stop Desc", "Road Desc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableBusRoute);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Route 1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(lRoadDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lBSDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lBSNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lBSNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lBSDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lRoadDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Route 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBusRoute;
    private javax.swing.JTable TableBuses;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lBSDesc;
    private javax.swing.JLabel lBSNumber;
    private javax.swing.JLabel lRoadDesc;
    // End of variables declaration//GEN-END:variables
}
