/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ajpassignment.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wee Kiat
 */
public class BusStopBrowserForm extends javax.swing.JDialog {

    /**
     * Creates new form BusStopBrowserForm
     */
    private BusStop Selection;
    private List<BusStop> bus_stops;
    
    public BusStopBrowserForm(javax.swing.JFrame owner) {
        super(owner,true);
        initComponents();
        
        Selection = null;
        setLocationRelativeTo(null);
        
        bus_stops = BusService.get().GetAllBusStop();
        DefaultTableModel model = (DefaultTableModel)TableBusStops.getModel();
        for(BusStop bs : bus_stops){
            model.addRow(new Object[]{ bs.GetBusStopCode(),bs.GetBusStopDesc(),bs.GetRoadDesc()});
        }
        
        TableBusStops.addMouseListener(new TableClickEvent(true, (Integer row) ->{
            Selection = bus_stops.get(row);
            setVisible(false);
            return null;
        }));
    }
    
    public BusStop GetSelection()
    {
        return Selection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableBusStops = new javax.swing.JTable();

        setTitle("Choose a bus stop...");

        TableBusStops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus Stop Code", "Bus Stop Desc", "Road Desc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableBusStops);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBusStops;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
